# Generated by Django 3.2 on 2023-06-19 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_profile_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
