# Generated by Django 3.2 on 2023-06-19 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='created_by',
            new_name='follower',
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='user',
            new_name='following',
        ),
    ]
