# Generated by Django 3.2 on 2023-06-20 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20230619_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='default_picture/default_profile.jpg', null=True, upload_to='profile_picture'),
        ),
    ]
